# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d66159c8667bec3e0669855cb42963f68e68c23c579e4eb33ef1260a547fdff018e20f1a9a5a03ef82341854d5d4622f7d53f2d6b929203e2b645025cac52cd8

test:
  secret_key_base: 2d013b93e7242ae407e811d26ef8f9a4343014437bcd098cbdbc537fcfe2539af47a3934152d4d04884bd31725aa3d8d43855d8e8f77ceb29b7551c680f96b4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
